//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patron { get; set; }
        public Nullable<int> ContractId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ClientsExtra ClientsExtra { get; set; }
    }
}
